In [2]:
import numpy as np

def cholesky(A):
    n = len(A)
    L = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            if j == i:
                L[i][j] = np.sqrt(A[i][i] - sum(L[i][k] ** 2 for k in range(j)))
            else:
                L[i][j] = (A[i][j] - sum(L[i][k] * L[j][k] for k in range(j))) / L[j][j]

    return L

def solve_cholesky(A, b):
    L = cholesky(A)

    # Forward substitution: Ly = b
    n = len(A)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - sum(L[i][j] * y[j] for j in range(i))) / L[i][i]

    # Backward substitution: L^Tx = y
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(L[j][i] * x[j] for j in range(i + 1, n))) / L[i][i]

    return x

In [4]:
mat = np.array([[0,1,2,-3,2,-2.5],
                [-5,5,-12,6,3,-3.5],
                [4,3,5,2,11,-9],
                [-5,-3,2,5,-7,27],
                [3,1,-4,9,5,-7]])


A = mat[:,:5]
b = mat[:,-1]


x = solve_cholesky(A, b)
print("Solution:", x)



Solution: [nan nan nan nan nan]


C:\Users\Admin\AppData\Local\Temp\ipykernel_15724\1658165372.py:12: RuntimeWarning: divide by zero encountered in scalar divide
  L[i][j] = (A[i][j] - sum(L[i][k] * L[j][k] for k in range(j))) / L[j][j]
C:\Users\Admin\AppData\Local\Temp\ipykernel_15724\1658165372.py:10: RuntimeWarning: invalid value encountered in sqrt
  L[i][j] = np.sqrt(A[i][i] - sum(L[i][k] ** 2 for k in range(j)))
C:\Users\Admin\AppData\Local\Temp\ipykernel_15724\1658165372.py:23: RuntimeWarning: divide by zero encountered in scalar divide
  y[i] = (b[i] - sum(L[i][j] * y[j] for j in range(i))) / L[i][i]


In [10]:
import numpy as np

# Kích thước của ma trận
n = 4

# Tạo một ma trận vuông đối xứng ngẫu nhiên
random_matrix = np.random.rand(n, n)
symmetric_matrix = random_matrix + random_matrix.T

# Thêm một ma trận đường chéo dương vào ma trận đối xứng
positive_diagonal = np.diag(np.random.rand(n) + 1)  # Thêm 1 để đảm bảo các giá trị dương
positive_definite_symmetric_matrix = symmetric_matrix + positive_diagonal

print("Ma trận đối xứng:")
print(symmetric_matrix)

print("\nMa trận đối xứng xác định dương:")
print(positive_definite_symmetric_matrix)

# Kiểm tra xem ma trận có xác định dương không
if np.all(np.linalg.eigvals(positive_definite_symmetric_matrix) > 0):
    print("Ma trận là ma trận đối xứng xác định dương.")
else:
    print("Ma trận không phải là ma trận đối xứng xác định dương.")


Ma trận đối xứng:
[[1.11260417 1.1077505  0.69463471 1.29668599]
 [1.1077505  0.62730767 1.53476811 0.87897224]
 [0.69463471 1.53476811 1.21959863 0.98991298]
 [1.29668599 0.87897224 0.98991298 0.48216343]]

Ma trận đối xứng xác định dương:
[[2.12049668 1.1077505  0.69463471 1.29668599]
 [1.1077505  2.47445127 1.53476811 0.87897224]
 [0.69463471 1.53476811 2.72335806 0.98991298]
 [1.29668599 0.87897224 0.98991298 2.06932764]]
Ma trận là ma trận đối xứng xác định dương.


In [5]:
[[0,1,2,-3,2,-2.5],
[-5,5,-12,6,3,-3.5],
[4,3,5,2,11,-9],
[-5,-3,2,5,-7,27],
[3,1,-4,9,5,-7]]


[[0, 1, 2, -3, 2, -2.5],
 [-5, 5, -12, 6, 3, -3.5],
 [4, 3, 5, 2, 11, -9],
 [-5, -3, 2, 5, -7, 27],
 [3, 1, -4, 9, 5, -7]]